### ISSUE TITLE
JTouchBar prevents JFrame to come visible (AWT)

### ISSUE THREAD

**Issue by blafois** [Thizzer/jtouchbar#10]
Hello!
Thanks for your great work!

Unfortunately I am unable to make the wrapper work.

JDK: Java(TM) SE Runtime Environment (build 1.8.0_151-b12)
OSX 10.13.3.

Having the JTouchBar in POM dependencies is enough to block the opening of JFrame, without any reference to JTouchBar in the code (even not in imports). If I want window to open, I need to remove it from dependencies and clean the project.
No error / stack trace is displayed - making it complex to debug.

Have tried recompiling the dylib as well as the lib, with both debug/release configuration.

Any idea or recommendations to obtain some log/traces ?

**Comment by ttveldhuis** [comment]
Are you using Eclipse to debug? If so, please try to use the solution described at https://github.com/Thizzer/JTouchBar/issues/6#issuecomment-349762148

I will probably create a separate pom for the SWT version of the project because that appears to be the root cause of all these issues.

**Comment by blafois** [comment]
Awesome! It works perfectly! I suggest adding this to the README!

2018-02-09 15:48 GMT+01:00 Thys ten Veldhuis <notifications@github.com>:

**Comment by ttveldhuis** [comment]
Opened #28 to help resolve this.

**Comment by ttveldhuis** [comment]
Fixed for 0.2.0 with #28
