### ISSUE TITLE
Display touchbar when app is out of focus

### ISSUE THREAD

**Issue by marlonbernardes** [Thizzer/jtouchbar#11]
Does this library support displaying a "fixed" touch bar? In other words, is it possible to configure the touch bar to be shown when the app is out of focus (similar to what Spotify does)?

Thanks in advance!

**Comment by ttveldhuis** [comment]
At the moment the library does not support that, Apple also states the following in the official [documentation](https://developer.apple.com/documentation/appkit/nstouchbar);

> On supported MacBook Pro models, the Touch Bar, above the keyboard, shows instances of the NSTouchBar class from the **front-most app**

But if there is a way to achieve this without it getting too hackish, I am willing to implement it. But I have not found a way to achieve this yet.

**Comment by marlonbernardes** [comment]
Electron also does not support this feature, AFAIK. Anyways, I'll let you know/open a PR if I find a not-so-hackish way of implementing this feature, then. Since this was merely a question (and I already have the answer), please feel free to close this issue if you want!
