### ISSUE TITLE
LWGL Support?

### ISSUE THREAD

**Issue by redwallhp** [Thizzer/jtouchbar#13]
I've been playing with JTouchBar a little lately, and was wondering if it would be possible for it to work with [LWGL](https://www.lwjgl.org/) applications? I picked through the source, but don't understand JNI enough to tell how viable it would be.

**Comment by ttveldhuis** [comment]
From what I’ve quickly seen looking at LWJGL examples, there is a pointer to the native window (which is the most important part) so I think this could easily be made possible. I will have a look at it as soon as possible.

**Comment by ttveldhuis** [comment]
Support for passing a raw pointer has been added to the latest snapshot (5e36c7d). This allows JTouchBar to be used with LWJGL. See the [Using JTouchBar with LWJGL](https://github.com/Thizzer/JTouchBar#using-jtouchbar-with-lwjgl) in the README for details.

**Comment by ttveldhuis** [comment]
5e36c7d
