### ISSUE TITLE
Support for enabling/disabling buttons

### ISSUE THREAD

**Issue by rdasilvacuriel** [Thizzer/jtouchbar#14]
I'd like to see support for enabling/disabling buttons. Right now I don't see any way to do this. I'm a Java/iOS developer myself so if it is possible/allowed I might try to add it myself.

**Comment by rdasilvacuriel** [comment]
I have it working locally for my situation in Swing with a simple login dialog that enables the login button on the touchbar only when the user has entered their username and when the password is sufficient to proceed. Will review and commit it somewhere today.

Compliments by the way on how easy it is to build and run the project(s) with XCode and Maven and how it integrates.

**Comment by ttveldhuis** [comment]
Sounds good, please create a pull request when you have the time 👍

**Comment by rdasilvacuriel** [comment]
Will do, but due to other commitments I'm a little delayed in finalising the code.

**Comment by rdasilvacuriel** [comment]
Pull request added. "Travis" fails, looks like it cannot find Mockito. No idea how Travis works and why it can't see Mockito when it is specified in the Maven pom.
