### ISSUE TITLE
Add support for adding scrollview with buttons

### ISSUE THREAD

**Issue by rdasilvacuriel** [Thizzer/jtouchbar#16]
Would be nice to be able to add a series of buttons through which the user can scroll. See: https://stackoverflow.com/questions/42123495/touch-bar-how-to-add-a-scrollable-list-of-buttons. For an example see the 'Calendar' application that allows selection of months from a horizontally scrolling list.

**Comment by ttveldhuis** [comment]
Adding UIScrollView support to the touchbar isn't really supported in a nice way by the OS. 

The Calendar app uses the NSScrubber for doing this which is currently already supported in JTouchBar.
