### ISSUE TITLE
System color support

### ISSUE THREAD

**Issue by olivernybroe** [Thizzer/jtouchbar#17]
It looks the colors have been hardcoded instead of it using system colors 
https://developer.apple.com/macos/human-interface-guidelines/touch-bar/touch-bar-visual-design/#color also called NSColors.

**Comment by olivernybroe** [comment]
Also most importantly the Dynamic System Colors would be really nice to have support for.

**Comment by ttveldhuis** [comment]
I will try to make the color class use the colors predefined in NSColor.

**Comment by ttveldhuis** [comment]
The colors are now dynamically resolved using the appropriate names instead of predefined RGBA values. All of the colors you need should be available through the Color class.

**Comment by olivernybroe** [comment]
Ill test this out later, thanks a lot.

**Comment by olivernybroe** [comment]
It works perfectly! `Color.CONTROL_COLOR` looks so good, thanks a lot for your work.
