### ISSUE TITLE
No colors match the default color

### ISSUE THREAD

**Issue by olivernybroe** [Thizzer/jtouchbar#18]
I cannot match the original color at all, tried all the colors, what am I doing wrong?
![image](https://user-images.githubusercontent.com/5870441/38316123-4aaa3b88-382a-11e8-9b81-51fe0810a512.png)
Its the button `works`, the color is off, it doesn't match the normal buttons
```
TouchBarButton touchBarButton = new TouchBarButton();
touchBarButton.setTitle("works");
touchBarButton.setBezelColor(Color.DARK_GRAY);
jTouchBar.addItem(new TouchBarItem("button_1", touchBarButton));
 ```

**Comment by ttveldhuis** [comment]
Related to #17

**Comment by ttveldhuis** [comment]
With the latest commit you should be able to use `Color.CONTROL_COLOR` for this.
