### ISSUE TITLE
Popovers

### ISSUE THREAD

**Issue by olivernybroe** [Thizzer/jtouchbar#19]
Could be nice if you could implement popovers
https://developer.apple.com/macos/human-interface-guidelines/touch-bar/touch-bar-controls-and-views#Popovers

**Comment by ttveldhuis** [comment]
Basic support has been added in the latest commit. I tagged it so a snapshot will be created.

Still need to add support for;
- showPopover
- dismissPopover
- showsCloseButton

**Comment by ttveldhuis** [comment]
Added support for ‘showsCloseButton’ but still missing the dismiss method to be able to dismiss the opened popover when ‘showsCloseButton’ is set to ‘false’.

**Comment by olivernybroe** [comment]
Amazing! Will try it out when I get some time free again.

**Comment by olivernybroe** [comment]
Something in your new code has changed. My code doesn't work anymore, it just crashes now, even though no changes has been made to my codebase.

**Comment by ttveldhuis** [comment]
I'll have a look at it as soon as possible. In the mean time, what type of elements are you adding to the touchbar? Or does it also crash with an empty touchbar?

**Comment by olivernybroe** [comment]
It crashes when running show after adding a button. If you can't recreate the error, I'll try and see if I can make a simple example which reproduces the error.

**Comment by ttveldhuis** [comment]
I've tried to reproduce by adding several elements (separately and together) but I can't seem to reproduce the crash. Could you try to write an example which crashes?

**Comment by olivernybroe** [comment]
Actually having some problems making the example. However in my project I can easily reproduce it.
I can tell you how to reproduce it in my project.

I can also give you the log? Maybe it might give you some insight?

**Comment by olivernybroe** [comment]
```
OpenJDK 64-Bit Server VM warning: ignoring option MaxPermSize=250m; support was removed in 8.0
objc[28164]: Class FIFinderSyncExtensionHost is implemented in both /System/Library/PrivateFrameworks/FinderKit.framework/Versions/A/FinderKit (0x7fff8dba6c90) and /System/Library/PrivateFrameworks/FileProvider.framework/OverrideBundles/FinderSyncCollaborationFileProviderOverride.bundle/Contents/MacOS/FinderSyncCollaborationFileProviderOverride (0x12c5d6cd8). One of the two will be used. Which one is undefined.
:runIde
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00000001048ec1df, pid=27043, tid=0x0000000000000307
#
# JRE version: OpenJDK Runtime Environment (8.0_152-b06) (build 1.8.0_152-release-1153-b6)
# Java VM: OpenJDK 64-Bit Server VM (25.152-b6 mixed mode bsd-amd64 compressed oops)
# Problematic frame:
# V  [libjvm.dylib+0x2ec1df]
#
# Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
#
# An error report file with more information is saved as:
# /Users/uruloke/.gradle/caches/modules-2/files-2.1/com.jetbrains.intellij.idea/ideaIC/LATEST-EAP-SNAPSHOT/71ffd116fca01d7bd4db1251b5e567b70d5e78e1/ideaIC-LATEST-EAP-SNAPSHOT/bin/hs_err_pid27043.log
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp
#
```

and the log file it refers to can be found here https://gist.github.com/olivernybroe/0adf0d1bebb4302434310fb9e9bc5e48

**Comment by olivernybroe** [comment]
For reproducing it in my project just clone https://github.com/olivernybroe/intellij-touch and change `build.gradle`.
In `build.gradle` replace 
```
compile files('libs/jtouchbar-0.1.0-SNAPSHOT.jar', 'libs/org.eclipse.swt.cocoa.macosx.x86_64-4.6.1.jar')
```
with
```
compile group: 'com.thizzer.jtouchbar', name: 'jtouchbar', version: '0.1.0-SNAPSHOT'
```

For running the code use `gradle runIde`.

(I'll try to see if I can make a simple example as my project is a plugin to IntelliJ, which adds a lot of other elements to look out for.)

**Comment by ttveldhuis** [comment]
I've added some additional (error) handling which appears to have solved the crash. When I use the latest jar from the [repository](https://oss.sonatype.org/#nexus-search;quick~jtouchbar) the plugin doesn't crash anymore. So after you've refreshed your dependencies it should work again.

**Comment by olivernybroe** [comment]
Cool, just tested and it works now!
Thanks a lot dude.
