### ISSUE TITLE
[Bug] Changes in new version crashes

### ISSUE THREAD

**Issue by olivernybroe** [Thizzer/jtouchbar#23]
Just changed to the newest version, but that results in a crash when starting up 
There has been no changes in my code and it works with an older version of JTouchbar.

```
:runIde
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x000000010bcec129, pid=14254, tid=0x0000000000010507
#
# JRE version: OpenJDK Runtime Environment (8.0_152-b06) (build 1.8.0_152-release-1153-b6)
# Java VM: OpenJDK 64-Bit Server VM (25.152-b6 mixed mode bsd-amd64 compressed oops)
# Problematic frame:
# V  [libjvm.dylib+0x2ec129]  jni_GetObjectClass+0x65
#
# Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
#
# An error report file with more information is saved as:
# /Users/uruloke/.gradle/caches/modules-2/files-2.1/com.jetbrains.intellij.idea/ideaIC/LATEST-EAP-SNAPSHOT/71ffd116fca01d7bd4db1251b5e567b70d5e78e1/ideaIC-LATEST-EAP-SNAPSHOT/bin/hs_err_pid14254.log
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp
#
:runIde FAILED
```

The log file referenced above can be found [here](https://gist.github.com/olivernybroe/888c49d8ecd86cd16117066a7b3d78b4).

Haven't been able to reproduce it in a simple example, not sure what the difference is in my project, sorry.

Sidenote: 
Could be nice if you changed the version when you make changes. So we can actually tell which version isn't working anymore.

**Comment by ttveldhuis** [comment]
I will have a look at this. 

In regards to the sidenote, I hope to soon move the snapshot to the release repository, after that version numbers will hopefully move more quickly.

**Comment by olivernybroe** [comment]
@ttveldhuis Sounds great. 
Sorry for not being able to give you a simple example to run.

**Comment by ttveldhuis** [comment]
Pushed a fix for the bug found in the log file. Hopefully that should fix your crash.

**Comment by olivernybroe** [comment]
I fixed the crash, but now there is no touchbar.

It also fails to show a touchbar in a simple example.
```
     JFrame frame = new JFrame();
        frame.add(new Button("works"));
        frame.pack();
        frame.setVisible(true);

        JTouchBar jTouchBar = new JTouchBar();
        jTouchBar.setCustomizationIdentifier("MySwingJavaTouchBar");

        // button
        TouchBarButton touchBarButtonImg = new TouchBarButton();
        touchBarButtonImg.setBezelColor(Color.CONTROL_COLOR);
        Image image = new Image(ImageName.NSImageNameTouchBarColorPickerFill, false);
        touchBarButtonImg.setImage(image);

        jTouchBar.addItem(new TouchBarItem("button_1", touchBarButtonImg));
        jTouchBar.show(frame);
```

**Comment by ttveldhuis** [comment]
My apologies, I was too quick with my change and made a mistake. I've pushed the fix.

**Comment by olivernybroe** [comment]
@ttveldhuis Great the example i provided works now. 
No need for apologising, I am just using your library, your the hero here.
