### ISSUE TITLE
[Bug] Halts/crashes? my UI thread

### ISSUE THREAD

**Issue by olivernybroe** [Thizzer/jtouchbar#24]
Sorry for this bug, I dont know if you can fix it as I really can't give you much information.

So in my plugin you can customize the touchbar as you like, after changing anything it calls `setItems(null)` and then `addItem` for each of the items. Afterwards it calls `show`, so it gets re-rendered. This is the same method that is called first time the touchbar appears and there is no problem there, only when trying to re-render the touchbar.

So when I call it this method for the second time, the whole UI freezes up and nothing responds. I have no idea how I can give you more info as it doesn't crash, it just freezes up.

This has worked before, last version it worked in was `jtouchbar-0.1.0-20180404.160200-10.jar`.

**Comment by olivernybroe** [comment]
A little more testing showed that running it in a separate thread made it more stable in the current version, however calling it twice in a row still crashes it.

Going back to `jtouchbar-0.1.0-20180404.160200-10.jar`, makes it stable, when running in a separate thread and when not in it's own thread.

**Comment by ttveldhuis** [comment]
Don’t apologize for finding bugs, only makes the project more stable in the end ;) 
I’ll have a look at it. Do you think I can reproduce it using the latest version of your source and the latest release of JTouchBar?

**Comment by olivernybroe** [comment]
Hehe true, just not much to go on ;)

You should be able to reproduce it with the latest edition (just commited).

**Comment by olivernybroe** [comment]
To reproduce do the following
- go to `preferences` -> `Appearences & Behavior` -> `Menus and Toolbar` -> `Touch Bar`.
- Spam click (twice should be enough) `Refresh touch bar` button and it should crash.

**Comment by ttveldhuis** [comment]
Pushed a possible fix (mentioned wrong issue in commit message #23 should be #24). I can't reproduce it anymore using this fix.

**Comment by olivernybroe** [comment]
Amazing! It looks like it works now, thanks a lot.
