### ISSUE TITLE
0.2.0-SNAPSHOT for maven repos

### ISSUE THREAD

**Issue by J4unty** [Thizzer/jtouchbar#32]
Hi

Could you please upload a SNAPSHOT release of the 0.2.0 version into the Maven repositories, so we can use it with Java 10 without putting a jar in our repositories.

Many Thanks 👍 
J4unty

**Comment by ttveldhuis** [comment]
There should already be a snapshot available;

```
<dependency>
	<groupId>com.thizzer.jtouchbar</groupId>
	<artifactId>jtouchbar</artifactId>
	<version>0.2.0-SNAPSHOT</version>
</dependency>
```

Aiming to release within the next two weeks.

**Comment by J4unty** [comment]
Thank you

J4unty
