### ISSUE TITLE
0.1.0 fails with error "Could not find org.eclipse.swt:org.eclipse.swt.cocoa.macosx.x86_64:4.6.1."

### ISSUE THREAD

**Issue by grimreaper** [Thizzer/jtouchbar#34]
### Steps to reproduce
1. Create new gradle project
2. As the only change add
```
implementation group: 'com.thizzer.jtouchbar', name: 'jtouchbar', version: '0.1.0'
```
as a dependency
3. Run `./gradlew compileJava`

### Actual Outcome
```
Execution failed for task ':compileJava'.
> Could not resolve all files for configuration ':compileClasspath'.
   > Could not find org.eclipse.swt:org.eclipse.swt.cocoa.macosx.x86_64:4.6.1.
     Searched in the following locations:
       - https://jcenter.bintray.com/org/eclipse/swt/org.eclipse.swt.cocoa.macosx.x86_64/4.6.1/org.eclipse.swt.cocoa.macosx.x86_64-4.6.1.pom
       - https://jcenter.bintray.com/org/eclipse/swt/org.eclipse.swt.cocoa.macosx.x86_64/4.6.1/org.eclipse.swt.cocoa.macosx.x86_64-4.6.1.jar
     Required by:
         project : > com.thizzer.jtouchbar:jtouchbar:0.1.0

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s
1 actionable task: 1 executed
```

### Expected Outcome

See a successful build.

### Additional Useful Details
Gradle 5.1.1
openjdk version "1.8.0_181"
```
∴sw_vers
ProductName:	Mac OS X
ProductVersion:	10.14.2
BuildVersion:	18C54
````

Let me know if there is anything else that might be helpful or if you can't reproduce.

If the issue is fixed already consider this a request for a release :)

### Quick Note
Thanks for working on this library!

**Comment by ttveldhuis** [comment]
If you are not using SWT the advice for now is to use the 0.2.0-SNAPSHOT version of JTouchbar, where SWT-support has been moved to a separate library.

```implementation group: 'com.thizzer.jtouchbar', name: 'jtouchbar', version: '0.2.0-SNAPSHOT'```

**Comment by grimreaper** [comment]
This might be my error, but it does seem to resolve. Is there an additional repo I need?

```
Execution failed for task ':compileJava'.
> Could not resolve all files for configuration ':compileClasspath'.
   > Could not find com.thizzer.jtouchbar:jtouchbar:0.2.0-SNAPSHOT.
     Searched in the following locations:
       - https://jcenter.bintray.com/com/thizzer/jtouchbar/jtouchbar/0.2.0-SNAPSHOT/maven-metadata.xml
       - https://jcenter.bintray.com/com/thizzer/jtouchbar/jtouchbar/0.2.0-SNAPSHOT/jtouchbar-0.2.0-SNAPSHOT.pom
       - https://jcenter.bintray.com/com/thizzer/jtouchbar/jtouchbar/0.2.0-SNAPSHOT/jtouchbar-0.2.0-SNAPSHOT.jar
     Required by:
         project :
```

**Comment by ttveldhuis** [comment]
Snapshots are currently only available in the Maven Central repository. You can add it to the repositories configuration in Gradle like this:

```gradle
repositories {
    mavenCentral()
}
```

**Comment by grimreaper** [comment]
perfect. thanks!

(will leave this open as a request to release, unless you'd prefer to close)

**Comment by ttveldhuis** [comment]
I've added this to the 1.0.0 milestone (previously 0.2.0). Hoping to create release this week.

**Comment by ttveldhuis** [comment]
Version 1.0.0 has been released and should resolve this issue. It might take a while until it is available in the repository.
