### ISSUE TITLE
[support] touchbar shows nothing

### ISSUE THREAD

**Issue by grimreaper** [Thizzer/jtouchbar#39]
How to reproduce:

1. Compile and run the test case provided below. 
2. ensure you're on the java application

What to expect: 
- A touchbar shown with a slider

What actually gets shown:
- an empty touchbar as if it was never initialized. 
![image](https://user-images.githubusercontent.com/433817/54109736-ba3c8b80-439c-11e9-8d0c-26c55d8fc9f9.png)

I'm unsure if I made a mistake, there is missing documentation, or if this is a bug.

```java
package touchbar;

import com.thizzer.jtouchbar.JTouchBar;
import com.thizzer.jtouchbar.item.TouchBarItem;
import com.thizzer.jtouchbar.item.view.TouchBarScrubber;

import javax.swing.JFrame;

public class App {

    public static void main(String[] args) {
          App app = new App();
          app.show();

          System.out.println("finished");
    }

     private final JTouchBar jTouchBar;
     private final JFrame frame;
	
     App() {
          jTouchBar = new JTouchBar();
          frame = new JFrame("JTouchBar");
          frame.pack();
    }
	
     private void show() {
          System.out.println("showing");
          frame.setVisible(true);

         TouchBarScrubber touchBarScrubber = new TouchBarScrubber();
         touchBarScrubber.setActionListener((scrubber, index) ->
                 System.out.println("Selected Scrubber Index: " + index));

         jTouchBar.addItem(new TouchBarItem("Scrubber_1", touchBarScrubber, true));

         System.out.println("enabling touchbar");
          jTouchBar.show(frame);

          System.out.println("enabled touchbar");
    }
}

```

**Comment by grimreaper** [comment]
I forgot to mention this:
```
∴java -version
openjdk version "11.0.2" 2019-01-15
OpenJDK Runtime Environment 18.9 (build 11.0.2+9)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.2+9, mixed mode)

∴sw_vers
ProductName:	Mac OS X
ProductVersion:	10.14.3
BuildVersion:	18D109
```

**Comment by ttveldhuis** [comment]
I've had a quick look in to it, but the scrubber is a beast of its own. If you call:

```touchBarScrubber.setShowsArrowButtons( true );```

Arrows should show on the left and right of the touchbar.

The scrubber relies on a datasource for the views it can present. An example of setting the datasource could be:

```
...

final List<ScrubberView> views = new ArrayList<>();

for(int idx = 1; idx <= 100; idx++)
{
	ScrubberTextItemView testView = new ScrubberTextItemView();
	testView.setStringValue("Index: " + idx);

	views.add(testView);
}

touchBarScrubber.setDataSource( new ScrubberDataSource() 
{
	@Override
	public ScrubberView getViewForIndex(TouchBarScrubber scrubber, long index) 
	{
		return views.get((int)index);
	}
			
	@Override
	public int getNumberOfItems(TouchBarScrubber scrubber) 
	{
		return views.size();
	}
});

...
```

Currently only the ScrubberTextItemView (displaying a text) and ScrubberImageItemView (displaying an image) are supported. I will add an issue for JTouchbar 1.1.0 for adding support for more scrubber views. 

Also I found that the TextItemView does not support resizing, so I will add an issue for that as well.

For more details on the scrubber take a look at the [documentation](https://developer.apple.com/documentation/appkit/nsscrubber?language=objc) apple provides. The java implementation of JTouchBar is trying to stay as close as possible to that implementation.

**Comment by grimreaper** [comment]
hrm. Interesting information and useful to know. I'll follow up (possibly on a separate issue) if in trying to use this in my application I run into more problems.

I wonder if it makes sense to throw an exception if you try to add slider without a DataSource?
