### ISSUE TITLE
AWTUtils.getViewPointer(Component component) cause NPE

### ISSUE THREAD

**Issue by rslama** [Thizzer/jtouchbar#4]
I tested this library (loaded from maven repo) within my testing java app and it alway produce NPE:

Exception in thread "main" java.lang.RuntimeException: java.lang.NullPointerException
	at com.thizzer.jtouchbar.awt.AWTUtils.getViewPointer(AWTUtils.java:25)
	at com.thizzer.jtouchbar.JTouchBar.enableForComponent(JTouchBar.java:60)
	at Start.init(Start.java:34)
	at Start.main(Start.java:23)
Caused by: java.lang.NullPointerException
	at com.thizzer.jtouchbar.awt.AWTUtils.getViewPointer(AWTUtils.java:19)
	... 3 more

Problematic line follow (AWTUtils: 24)
Object peer = Component.class.getMethod("getPeer").invoke(component);

where peer object return null and next line (of course) end up NPE.

any idea?

**Comment by ttveldhuis** [comment]
What object/class are you passing to the ‘enableForComponent’ method?

**Comment by rslama** [comment]
I followed example so here is that piece:
        JFrame frame = new JFrame();
        JTouchBar jTouchBar = new JTouchBar();
        jTouchBar.setCustomizationIdentifier("TouchBar");
        jTouchBar.enableForComponent(frame);

frame is of course javax.swing.JFrame

same NPE in case of use Frame from awt package

**Comment by ttveldhuis** [comment]
Hmm.. This should of course just work. I will look in to this, what version of macOS and Java are you using?

**Comment by rslama** [comment]
jdk1.8.0_152
macOS Sierra 10.12.6

**Comment by ttveldhuis** [comment]
The way I can reproduce this is when `JFrame.pack();` and/or`JFrame.setVisible(true);` have not been called.

So you have to properly initialise your JFrame, this should go as follows;

```
JFrame frame = new JFrame();
// .. add stuff to frame
frame.pack();
frame.setVisible(true);

JTouchBar jTouchBar = new JTouchBar();
jTouchBar.setCustomizationIdentifier("TouchBar");
jTouchBar.enableForComponent(frame);
```

Could you please let me know if this works? I will try to add a more elaborate examples in the future.

**Comment by rslama** [comment]
Hey, with pack() && setVisible() that works as charm :)

**Comment by ttveldhuis** [comment]
Thats good to hear 👍 

Please let me know if you have any suggestions for the library or features you would like to see added.
