### ISSUE TITLE
Put in Module for Java 9+ Compatibility

### ISSUE THREAD

**Issue by DraqueT** [Thizzer/jtouchbar#50]
Could this be put into a module so that it could be built more easily with Java 9+? Specifically, this would allow it to be built into runnable images, which is how I distribute my software.

Thank you for making such a cool utility! I am really excited to integrate it and give my users some more flash if it can be pulled into a module!

**Comment by ttveldhuis** [comment]
@DraqueT I don't have a lot of experience with Java modules so it will take me a while to get to this. So you are more than welcome to submit a PR for this.

**Comment by DraqueT** [comment]
I'll take a crack at this, sure! Would you be open to moving to J9 yourself, or are you looking to stick with J8?
