### ISSUE TITLE
Add menus to the touch bar

### ISSUE THREAD

**Issue by ghost** [Thizzer/jtouchbar#52]
Like when you press one button it changes the touch bar to show a different set of buttons and changes the escape button to an x

Is this already a thing that I'm missing?

**Comment by TylerADavis** [comment]
You might be looking for popovers, but I'm not sure

https://github.com/Thizzer/jtouchbar/blob/7143b630f2aadd132beb5a758a1ad09f7cae2538/src/main/java/com/thizzer/jtouchbar/item/PopoverTouchBarItem.java

See the popover section in apple's documentation
https://developer.apple.com/design/human-interface-guidelines/macos/touch-bar/touch-bar-controls-and-views/

**Comment by ghost** [comment]
oh, that's exactly what I was looking for! Thanks. Didn't know JTouchBar supported this.
