### ISSUE TITLE
SF Symbols images

### ISSUE THREAD

**Issue by kloenk** [Thizzer/jtouchbar#58]
It would be nice I one could just select the SF Symbols to use on the Touch Bar, without the need to provide it manually.

**Comment by ttveldhuis** [comment]
Sorry for the late reply.

Could you elaborate on this? Currently it's possible to use built-in images by using ImageName, eg:

```
// button
TouchBarButton touchBarButtonImg = new TouchBarButton();
...
Image image = new Image();
img.setName(ImageName.NSImageNameTouchBarColorPickerFill); // Here the built-in image is specified
touchBarButtonImg.setImage(image);
...
```

**Comment by kloenk** [comment]
It's probably what I searched for, just didn't found it.
