### ISSUE TITLE
Swing - Frame never shows

### ISSUE THREAD

**Issue by AJNeufeld** [Thizzer/jtouchbar#6]
I tried to get JTouchBar working with Swing, but the code alway hangs when making the JFrame visible.  I modelled the test application after `com.thizzer.jtouchbar.awt.JTouchBarAWTTest`:

```
public class App {

    public static void main(String[] args) throws InvocationTargetException, InterruptedException {
          App app = new App();

          int invoke = 0;
          if (invoke == 0)	
               SwingUtilities.invokeAndWait(app::show);
          else if (invoke == 1)
               SwingUtilities.invokeLater(app::show);
          else
               app.show();

          System.out.println("finished");
    }

     final JTouchBar jTouchBar;
     final JFrame frame;
	
     App() {
          jTouchBar = JTouchBarTestUtils.constructTouchBar();
          Objects.nonNull(jTouchBar);
		
          JFrame.setDefaultLookAndFeelDecorated(true);
          frame = new JFrame("JTouchBar");
          frame.pack();
    }
	
     void show() {
          System.out.println("showing");
          frame.setVisible(true);

          System.out.println("enabling touchbar");
          jTouchBar.enableForComponent(frame);

          System.out.println("enabled touchbar");
    }
}
```

When `invokeAndWait` is used, I get:
> showing

When `invokeLater` is used, I get:
> finished
> showing

When `setVisible` is called from the main thread (like in `com.thizzer.jtouchbar.awt.JTouchBarAWTTest`), the main thread runs to completion:
> showing
> enabling touchbar
> enabled touchbar
> finished

In all of these cases, the `JFrame` never actually appears, and the application must be terminated manually. 

When similar code is run as a JUnit test, when the test is complete, when the main thread exits, the background thread is killed by the JUnit test environment, so the test appears to pass.  The JFrame never appears.

jdk1.8.0_121
macOS 10.13.1 (High Sierra)

**Comment by AJNeufeld** [comment]
Stack Trace from the `invokeAndWait` case:

> owns: Component$AWTTreeLock  (id=44)	
> CWrapper$NSWindow.isZoomed(long) line: not available [native method]	
> CPlatformWindow.isMaximized() line: 476	
> CPlatformWindow.setVisible(boolean) line: 530	
> LWWindowPeer.setVisibleImpl(boolean) line: 248	
> LWWindowPeer(LWComponentPeer<T,D>).setVisible(boolean) line: 765	
> JFrame(Component).show() line: 1638	
> JFrame(Window).show() line: 1042	
> JFrame(Component).show(boolean) line: 1671	
> JFrame(Component).setVisible(boolean) line: 1623	
> JFrame(Window).setVisible(boolean) line: 1014	
> App.show() line: 46

**Comment by AJNeufeld** [comment]
Problem persists after upgrading to jdk1.8.0_151

**Comment by ttveldhuis** [comment]
Are you by any chance trying to run from Eclipse? If so, could you try running from, for example a commandline to see what happens?

**Comment by AJNeufeld** [comment]
Yes, running from eclipse.

Interesting, running from the command line, `invokeAndWait()` properly shows the JFrame.

So, what is up with Eclipse, and is there a work-around?

---

When run from from the command-line, with java 9, it crashes.  But that is a different issue.
```
showing
enabling touchbar
Exception in thread "main" java.lang.reflect.InvocationTargetException
	at java.desktop/java.awt.EventQueue.invokeAndWait(EventQueue.java:1328)
	at java.desktop/java.awt.EventQueue.invokeAndWait(EventQueue.java:1303)
	at java.desktop/javax.swing.SwingUtilities.invokeAndWait(SwingUtilities.java:1475)
	at ca.seinesoftware.touchbar.Main.main(Main.java:20)
Caused by: java.lang.RuntimeException: java.lang.NoSuchMethodException: java.awt.Component.getPeer()
 	at com.thizzer.jtouchbar.awt.AWTUtils.getViewPointer(AWTUtils.java:25)
 	at com.thizzer.jtouchbar.JTouchBar.enableForComponent(JTouchBar.java:60)
 	at ca.seinesoftware.touchbar.App.show(Main.java:49)
 	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:303)
```

**Comment by ttveldhuis** [comment]
I have seen this issue before and I will do some more research on it, from what I can quickly gather is that it is somehow related to the fact that the library is also dependent on SWT.

**Comment by ttveldhuis** [comment]
I have found a solution/workaround. There is an option the `Run/Debug Configurations` in Eclipse stating;

_'Use the -XstartOnFirstThreadArgument when launching with SWT'_ 

Disabling this option appears to do the trick. (See screenshot for more details). I haven't found a bug report for Eclipse for this yet, so maybe there is something we can do in the library to prevent you from having to do this, but I'll do some more research and come back to this when I have more information. I hope for now this `workaround` will solve your problem.

![screen shot 2017-12-06 at 21 11 54](https://user-images.githubusercontent.com/1822698/33683314-c649c88e-daca-11e7-9614-f94b5bbc6bcc.png)

**Comment by ttveldhuis** [comment]
https://bugs.eclipse.org/bugs/show_bug.cgi?id=212617

**Comment by ttveldhuis** [comment]
@AJNeufeld can you confirm that disabling the run configuration option makes it work?

**Comment by AJNeufeld** [comment]
Yes - confirmed - unchecking the "Use the -XstartOnFirstThread argument when launching with SWT" allows JToolBar to work with AWT/Swing.
